export default [{
  id: 1,
  img: '/assets/images/home/photographer.jpg',
  title: 'Photography Masterclass: Your Complete Guide to Photography',
  desc: 'The Best Online Professional Photography Class: How to Take Amazing Photos for Beginners and Advanced Photographers',
  teacher: 'Determined Poitras',
  category: 'photography',
  duration: '2 Weeks',
  students: 120,
  price: 165
},
  {
    id: 2,
    img: '/assets/images/home/learning1.png',
    title: 'The Complete Full-Stack Web Development BootcampBecome',
    desc: 'a Full-Stack Web Developer with just ONE course. HTML, CSS, Javascript, Node, React, PostgreSQL, Web3',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '120 min',
    students: 2,
    price: 0
  },
  {
    id: 3,
    img: '/assets/images/home/learning2.png',
    title: 'The Complete JavaScript Course 2025: From Zero to Expert!',
    desc: 'The modern JavaScript course for everyone! Master JavaScript with projects, challenges and theory. Many courses in one!',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '1 Week',
    students: 300,
    price: 120
  },
  {
    id: 4,
    img: '/assets/images/home/student.jpg',
    category: 'photography',
    title: 'THE Photography Masterclass: Complete Course on Photography',
    desc: 'Learn how to create amazing images for beginners & advanced photographers. The only photography course you need.',
    teacher: 'Determined-Poitras',
    duration: '2 Days',
    students: 1230,
    price: 0
  },
  {
    id: 5,
    img: '/assets/images/home/learning3.png',
    title: 'Angular - The Complete Guide (2025 Edition)',
    desc: 'Master Angular (formerly "Angular 2") and build awesome, reactive web apps with the successor of Angular.js',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '2 Weeks',
    students: 5,
    price: 200
  },
  {
    id: 6,
    img: '/assets/images/home/finance.jpg',
    title: 'The Complete Financial Analyst Course 2025',
    desc: 'Excel, Accounting, Financial Statement Analysis, Business Analysis, Financial Math, PowerPoint: Everything is Included!',
    teacher: 'Chris Haroun',
    category: 'finance',
    duration: '2 Weeks',
    students: 5,
    price: 200
  },
  {
    id: 7,
    img: '/assets/images/home/finance1.jpg',
    title: 'Introduction to Finance, Accounting, Modeling and Valuation',
    desc: 'Learn Finance & Accounting from Scratch by an Award Winning MBA Professor, Ivy Grad, worked @ Goldman & VC',
    teacher: 'Chris Haroun',
    category: 'finance',
    duration: '2 Weeks',
    students: 415,
    price: 200
  },
  {
    id: 8,
    img: '/assets/images/home/front3.png',
    title: 'Build Responsive Real-World Websites with HTML and CSS',
    desc: 'Learn modern HTML5, CSS3 and web design by building a stunning website for your portfolio! Includes flexbox and CSS Grid',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '2 Weeks',
    students: 500,
    price: 200
  },
  {
    id: 9,
    img: '/assets/images/home/back2.png',
    title: 'Python and Django Full Stack Web Developer',
    desc: 'Learn to build websites with HTML , CSS , Bootstrap , Javascript , jQuery , Python 3 , and Django!',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '2 Weeks',
    students: 723,
    price: 200
  },
  {
    id: 10,
    img: '/assets/images/home/finance.jpg',
    title: 'The Complete Finance Manager Course',
    desc: 'Financial Management, ERP systems, Accounting, Capital budgeting, Presentation design, Management, and Negotiation',
    teacher: 'Chris Haroun',
    duration: '2 Weeks',
    category: 'finance',
    students: 5,
    price: 200
  },
  {
    id: 11,
    img: '/assets/images/home/back1.png',
    title: 'The Complete ASP.NET MVC 5 Course',
    desc: 'Learn to build fast and secure web applications with ASP.NET MVC 5 - The most popular course with 40,000+ students!\n',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '2 Weeks',
    students: 5,
    price: 200
  },
  {
    id: 12,
    img: '/assets/images/home/back3.jpg',
    category: 'development',
    title: 'Learn and Understand NodeJS',
    desc: 'Dive deep under the hood of NodeJS. Learn V8, Express, the MEAN stack, core Javascript concepts, and more.',
    teacher: 'Roza Shafiei',
    duration: '2 Weeks',
    students: 5,
    price: 200
  },
  {
    id: 13,
    img: '/assets/images/home/front2.jpg',
    title: 'Complete React Developer (w/ Redux, Hooks, GraphQL)',
    desc: 'Updated! Become a Senior React Developer. Build a massive E-commerce app with Redux, Hooks, GraphQL, Stripe, Firebase',
    category: 'development',
    teacher: 'Roza Shafiei',
    duration: '2 Weeks',
    students: 800,
    price: 200
  },
  {
    id: 14,
    img: '/assets/images/home/front1.jpg',
    title: 'Modern HTML & CSS From The Beginning 2.0 (2024 Revamp)',
    desc: 'Build modern responsive websites with HTML and CSS - Learning modules, mini-projects and 3 full websites',
    teacher: 'Roza Shafiei',
    category: 'development',
    duration: '2 Weeks',
    students: 320,
    price: 200
  },
  {
    id: 15,
    img: '/assets/images/home/marketing1.png',
    title: 'The Complete Digital Marketing Guide',
    desc: 'Digital Marketing, Social Media, ChatGPT, Prompt Engineering, Google Ads, Facebook, SEO, WordPress, Instagram, YouTube.',
    teacher: 'Robin & Jesper',
    category: 'marketing',
    duration: '2 Weeks',
    students: 20,
    price: 89.99
  },
  {
    id: 15,
    img: '/assets/images/home/marketing2.jpg',
    title: 'Mega Digital Marketing Course A-Z',
    desc: 'Digital Marketing Strategy, Social Media Marketing, WordPress, SEO, ChatGPT, Email, Instagram, Facebook, YouTube, ads',
    teacher: 'Robin & Jesper',
    category: 'marketing',
    duration: '2 Weeks',
    students: 56,
    price: 123
  },
  {
    id: 16,
    img: '/assets/images/home/marketing3.png',
    title: 'Marketing Psychology and Consumer Behavior',
    desc: 'Apply consumer behaviour, marketing psychology and behavior economics to skyrocket your rate of sales and conversions.',
    teacher: 'Robin & Jesper',
    category: 'marketing',
    duration: '2 Weeks',
    students: 56,
    price: 123
  },
  {
    id: 17,
    img: '/assets/images/home/marketing4.jpg',
    title: 'Business Fundamentals: Marketing Strategy',
    desc: 'Marketing Strategy Fundamentals: The Art Of Selling Your Products Through Superb Marketing Efforts',
    teacher: 'Robin & Jesper',
    category: 'marketing',
    duration: '2 Weeks',
    students: 198,
    price: 79
  },
  {
    id: 18,
    img: '/assets/images/home/photo1.png',
    title: 'Ultimate Guide to Landscape and Nature Photography',
    desc: 'Learn how lighting, composition, and photography techniques help you create stunning landscape and nature photography\n',
    teacher: 'Determined Poitras',
    category: 'photography',
    duration: '2 Weeks',
    students: 234,
    price: 89.99
  },
  {
    id: 19,
    img: '/assets/images/home/photo2.png',
    title: 'Product Photography: Beginner\'s Guide to Captivating Visuals',
    desc: 'Learn About Digital Camera Settings, Lighting Techniques, Composition Guides, Storytelling, Props, and Styling.',
    teacher: 'Determined Poitras',
    category: 'photography',
    duration: '2 Weeks',
    students: 67,
    price: 69
  },
  {
    id: 20,
    img: '/assets/images/home/photo3.png',
    title: 'Real Estate Photography Masterclass: Your Complete Guide',
    desc: 'You can capture & edit professional real estate photography & architecture photography with this easy-to-watch course!',
    teacher: 'Determined Poitras',
    category: 'photography',
    duration: '2 Weeks',
    students: 20,
    price: 19.99
  }
]
